// This file was generated by Prisma
import "dotenv/config";
import { defineConfig } from "prisma/config";
import data from "../config.json"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `file:../${data.database_config.db_name}.db`,
  },
});
